import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { FC, useEffect, useState, Fragment } from "react";
import Navbar from "../../components/Navbar";
import Layout from "../../components/Layout";
function classNames(...classes: any[]) {
  return classes.filter(Boolean).join(" ");
}

interface Props {}

const Directory: NextPage<Props> = () => {
  return (
    <Layout>
      <Head>
        <title>Velaa langsuan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-h-max h-screen w-full overflow-hidden  px-16 pt-32">
        <div className="w-full h-[700px]  relative">
          <Image
            src={"/assets/velaa-plan.png"}
            alt="map"
            fill
            style={{ objectFit: "contain", objectPosition: "top" }}
          />
        </div>
      </div>
    </Layout>
  );
};

export default Directory;
